name: Deploy MultiDocker
on:
  push:
    branches:
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Running deploy scripts
        run: |-
          docker build -t azeemzaidi/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true azeemzaidi/react-test npm test
          docker build -t azeemzaidi/multi-client-10-14 ./client
          docker build -t azeemzaidi/multi-nginx-10-14 ./nginx
          docker build -t azeemzaidi/multi-server-10-14 ./server
          docker build -t azeemzaidi/multi-worker-10-14 ./worker
          docker push azeemzaidi/multi-client-10-14
          docker push azeemzaidi/multi-nginx-10-14
          docker push azeemzaidi/multi-server-10-14
          docker push azeemzaidi/multi-worker-10-14
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v19
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: Multidocker-env
          existing_bucket_name: elasticbeanstalk-ap-southeast-2-254873692033
          region: ap-southeast-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip